version: '3'

services:
  db:
    image: postgres
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file:  '5'
    environment:
      POSTGRES_DB: gobarber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
    ports:
      - '4587:5432'
  redis:
    image: redis:alpine
    ports:
      - "4365:6379"
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file:  '5'
  mongo:
    image: mongo
    ports:
      - "3685:27017"
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file:  '5'
