version: '3'

services:
  db:
    image: postgres
    logging:
      driver: none
      options:
        max-size: '10m'
        max-file: '5'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
    ports:
      - ${PG_PORT}:80
    depends_on:
      - db
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
